create table if not exists public.exhibition_guestbook (
  id bigint generated by default as identity primary key,
  exhibition_id text not null,
  nickname text not null check (char_length(nickname) between 1 and 30),
  message text not null check (char_length(message) between 1 and 300),
  created_at timestamptz not null default now()
);

alter table public.exhibition_guestbook enable row level security;

create policy "guestbook entries are publicly readable"
on public.exhibition_guestbook
for select
to anon
using (exhibition_id = '2026-2-attraction');

create policy "visitors can add attraction guestbook entries"
on public.exhibition_guestbook
for insert
to anon
with check (
  exhibition_id = '2026-2-attraction'
  and char_length(nickname) between 1 and 30
  and char_length(message) between 1 and 300
);

revoke update, delete on public.exhibition_guestbook from anon;
